apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tour-package-be-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: 2306275203-be.hafizmuh.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tour-package-be-service
                port:
                  number: 80