apiVersion: v1
kind: Service
metadata:
  name: tour-package-be
spec:
  selector:
    app: tour-package-be
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP