apiVersion: v1
kind: Service
metadata:
  name: tour-package-be-service
spec:
  selector:
    app: tour-package-be
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP