name: Deploy Tour Package BE

on:
  push:
    branches:
      - 'main'

env:
  DOCKER_IMAGE_NAME: malikaatha/tour-package-be

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle (skip tests)
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: |
            build/libs/*.jar
            Dockerfile
            k8s/

  docker-push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: .
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker-push
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: .

      # Langkah 1: Siapkan file konfigurasi
      - name: Prepare configuration files
        run: |
          # Ganti tag image
          sed -i "s|REPLACE_ME_TAG|${{ github.sha }}|g" k8s/deployment.yaml
          
          # Buat ConfigMap
          printf "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: tour-package-be-config\ndata:\n  DATABASE_URL_PROD: \"${{ secrets.DATABASE_URL_PROD }}\"\n  DATABASE_USERNAME: \"${{ secrets.DATABASE_USERNAME }}\"\n" > k8s/configmap.yaml
          
          # Buat Secret
          printf "apiVersion: v1\nkind: Secret\nmetadata:\n  name: tour-package-be-secret\ntype: Opaque\nstringData:\n  DATABASE_PASSWORD: \"${{ secrets.DATABASE_PASSWORD }}\"\n  JWT_SECRET_KEY: \"${{ secrets._SECRET_KEY }}\"\n" > k8s/secret.yaml

      - name: Copy files to EC2 server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script_before: |
            rm -rf ~/app/tour-package-be/k8s
            mkdir -p ~/app/tour-package-be
          source: "k8s"
          target: "~/app/tour-package-be"

      - name: Apply Kubernetes configurations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "=== Cek File di Server ==="
            ls -la ~/app/tour-package-be/k8s/
            
            echo "=== Apply Konfigurasi ==="
            sudo k3s kubectl apply -f ~/app/tour-package-be/k8s/
            
            echo "=== Cek Status Deployment ==="
            # Force restart biar image baru ketarik (opsional tapi bagus)
            sudo k3s kubectl rollout restart deployment/tour-package-be
            sudo k3s kubectl rollout status deployment/tour-package-be